default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  username: <%= ENV.fetch('POSTGRES_USER') { '' } %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>

development:
  <<: *default
  database: controlled_health_api_development

test:
  <<: *default
  database: controlled_health_api_test

production:
  <<: *default
  database: controlled_health_api_production
  username: controlled_health_api
  password: <%= ENV['CONTROLLED_HEALTH_API_DATABASE_PASSWORD'] %>
